### PR TITLE
Implement std::error::Error

### PR DESCRIPTION
**Pull request by andber1**
I have added a "std" feature and the missing implementations for "Error" so that you can benefit from the std::error::Error features when working in a std environment.

### CODE REVIEW

**Comment by tarcieri** [comment]
You will need to modify the CI build job since it builds for a `no_std` target

**Comment by andber1** [comment]
What do you think is the best way? Just build with all features on a target supporting std? So that there is a build with default features on thumbv7em-none-eabihf and one build with all features on the ubuntu machine?

**Comment by tarcieri** [comment]
The `build` step is really there to check that that it builds on `no_std` targets and should probably be named something like `no_std` instead.

You can test all features but `std` in the `build` step. The tests with `--all-features` should cover that the `std` feature builds on a target that links `std`.

**Comment by tarcieri** [comment]
Thanks!

**Pull request merged**
