### PR TITLE
Added the accel_norm method to Accelerometer trait

### PR DESCRIPTION
**Pull request by gerber4**

### CODE REVIEW

**Comment by tarcieri** [comment]
I'm wondering if it might make sense to split `accel_raw` into its own trait, rather than require every accelerometer implement all three of these methods.

**Comment by gerber4** [comment]
In my opinion, any basic accelerometer should be able to implement accle_norm. For the perspective of a consumer of this trait, the consumer needs a way to interpret the acceleration data to perform tasks like positional tracking. Accel_norm does that interpretation on a chip by chip basis for the consumer.

**Comment by gerber4** [comment]
I feel the same about the sample_rate method, but that's just what I think right now. Using multiple traits could be valuable.

**Comment by tarcieri** [comment]
I guess we can try this and see what sort of feedback we get from downstream driver implementors

**Comment by tarcieri** [comment]
Will give this a try with the `adxl343` crate via git and then cut another release if I think it's all good

**Comment by gerber4** [comment]
I've created an rough implementation of the the new trait for the lis3dsh chip if you want to see an example. 

Also, because we are targeting embedded environments we may want to use integers instead of floats. For example, using an i32 representing mili-g instead of a float representing g.

**Comment by tarcieri** [comment]
I think that will really depend on what algorithms you intend to feed this data into and whether or not the device has an FPU or not.

If you're using this data as an input into e.g. AHRS (or pretty much anything computing spatial rotations with quaternions) you will almost certainly want floats.

Also note that the vectors are based on [micromath](https://docs.rs/micromath/) which is able to perform many floating point operations using bitwise/integer arithmetic by using fast approximations.

**Comment by tarcieri** [comment]
@JosephBGerber after poking at this, there are a few reasons why I think `Accelerometer` and a trait like `RawAcceleration` should be split in two:

- If it weren't for the `accel_raw` method, the `Accelerometer` trait could be object safe
- Some accelerometers support obtaining data in multiple different formats (e.g. both integer and floating point formats), and in those cases it'd be nice to be able to impl the `accel_raw` trait multiple times for different types

**Pull request merged**
