### PR TITLE
Upgrade to `micromath` v2.0

### PR DESCRIPTION
**Pull request by embediver**
To upgrade to `micromath` v2.0, few minimal changes were needed to comply with the refactored vector types.

### CODE REVIEW

**Comment by embediver** [comment]
Completely oversaw that the pipeline and the specified MSRV don't comply with the MSRV of micromath anymore...

Should I just bump the MSRV if favor for this?

**Comment by tarcieri** [comment]
Yes, bumping MSRV is fine

**Comment by tarcieri** [comment]
@MG-96 looks like one new clippy nit:

```
error: match expression looks like `matches!` macro
```

**Comment by embediver** [comment]
Should I fix them even though they don't have anything todo with the pr?

**Comment by tarcieri** [comment]
Yes, `clippy` needs to be clean to land the PR

**Pull request merged**
